# Generated by Django 5.2.7 on 2025-10-27 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('tipo', models.CharField(choices=[('C', 'Clínica'), ('T', 'Terapeuta'), ('F', 'Familiar')], default='F', max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('usuario_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contas_clinica', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'clínica',
                'verbose_name_plural': 'clínicas',
            },
            bases=('contas.usuario',),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('usuario_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contas_familiar', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'familiar',
                'verbose_name_plural': 'familiares',
            },
            bases=('contas.usuario',),
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('usuario_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contas_terapeuta', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crp', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'terapeuta',
                'verbose_name_plural': 'terapeutas',
            },
            bases=('contas.usuario',),
        ),
    ]
