# Generated by Django 5.2.7 on 2025-10-29 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorClinica',
            fields=[
                ('usuario_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contas_administrador_clinica', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj_clinica', models.CharField(blank=True, max_length=18, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'administrador da clínica',
                'verbose_name_plural': 'administradores da clínica',
            },
            bases=('contas.usuario',),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='telefone',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terapeutas', to='contas.clinica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admClinica', 'Administrador da Clínica'), ('clinica', 'Clínica'), ('terapeuta', 'Terapeuta'), ('familiar', 'Familiar')], default='familiar', max_length=20),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('concluido', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contas.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('neurodivergencia', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_vinculados', to='contas.clinica')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='pacientes_responsaveis', to='contas.familiar')),
                ('terapeutas', models.ManyToManyField(blank=True, related_name='pacientes_terapeutas', to='contas.terapeuta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_feedback', models.CharField(choices=[('comentario', 'Comentário'), ('progresso', 'Relato de Progresso'), ('ajuste', 'Sugestão de Ajuste')], max_length=20)),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('resposta', models.TextField(blank=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.familiar')),
                ('terapeuta_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.terapeuta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('caminho_arquivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(max_length=50)),
                ('tamanho_arquivo', models.IntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='contas.paciente'),
        ),
        migrations.CreateModel(
            name='PlanoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_terapeuticos', to='contas.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('anexos', models.ManyToManyField(blank=True, to='contas.documento')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='contas.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('duracao', models.IntegerField(help_text='Duração em minutos')),
                ('observacao', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='contas.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.terapeuta')),
            ],
        ),
    ]
